### ISSUE TITLE
Update to KSP 1.12.5 or 1.12.x

### ISSUE THREAD

**Issue by mariusfranzen** [sswelm/KSP-Interstellar-Extended#721] opened 2023-01-16 11:29 UTC
Does this already work for 1.12.5 or does it need updating?

**Comment by sswelm** [comment] 2023-01-16 12:08
It should be compatible unless proven otherwise

**Comment by GreenKeldeo** [comment] 2023-03-07 22:35
@sswelm I can confirm that KSPIE seems to work properly on 1.12.5, but you may want to update the CKAN version to 1.12.x as to avoid confusion

**Comment by sswelm** [comment] 2023-03-08 10:56
how to do that exactly?

here is the config file:

https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/KSPInterstellarExtended.netkan

**Comment by GreenKeldeo** [comment] 2023-03-09 02:26
@sswelm https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md#ksp_version

**Comment by GreenKeldeo** [comment] 2023-03-09 02:28
> @sswelm https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md#ksp_version

This is to say,
ksp_version_strict = false 
ksp_version_min = {minimum ksp version - could be 1.12}
ksp_version_max = {max ksp version, might work well as 1.12.9}

**Comment by GreenKeldeo** [comment] 2023-03-09 02:29
Sorry about not formatting it; I'm on my phone at the moment so I can't put it in JSON properly

**Comment by sswelm** [comment] 2023-03-09 07:36
Alright, I created a PR at https://github.com/KSP-CKAN/NetKAN/pull/9610

lets hope the gods are willing

**Comment by HebaruSan** [comment] 2023-03-09 07:40
You could update the remote version file to reflect current compatibility, that's what it's for:

https://ksp-avc.cybutek.net/version.php?id=152

**Comment by sswelm** [comment] 2023-03-09 07:43
@HebaruSan   How to update that file?

**Comment by HebaruSan** [comment] 2023-03-09 07:45
However you initially created it, I guess. I haven't used cybutek.net, but I would assume you created a login and password there at some point, maybe?

If you can't access it, then it would be a good idea to stop using it and switch to something on GitHub (for example).

**Comment by sswelm** [comment] 2023-03-09 07:49
I guess I need to update the mod at https://spacedock.info/mod/172/KSP%20Interstellar%20Extended without sending 500 emails

**Comment by HebaruSan** [comment] 2023-03-09 07:50
For now the CKAN change is fine as a workaround, but I try to spread knowledge of version files when possible, since it's generally the easier solution.

**Comment by GreenKeldeo** [comment] 2023-03-09 19:27
@sswelm may want to close this ticket once the PR is approved

**Comment by HebaruSan** [comment] 2023-03-09 19:28
@GreenKeldeo the compatibility was updated about 3 hours ago:

https://github.com/KSP-CKAN/CKAN-meta/commit/b675e717b5880877bccabb28a299b5a5cbb64270

**Comment by GreenKeldeo** [comment] 2023-03-09 20:25
@HebaruSan Thanks; would close this ticket, but it wasn't made by me

**Closed** 2023-03-09 22:39 UTC
