### ISSUE TITLE
Scaling Up Microwave Phased Array Transceiver Lowers Mass

### ISSUE THREAD

**Issue by NachtRaveVL** [sswelm/KSP-Interstellar-Extended#65] opened 2017-04-23 03:32 UTC
Scaling this part up, along with the deployable phased array, causes the total mass to decrease instead of increase.

Maybe a missed negative sign?

**Comment by arivaldh** [comment] 2018-03-13 18:37
I don't know which part is that right now. @sswelm could you confirm that the issue is still valid?

**Comment by sswelm** [comment] 2018-03-13 22:15
I will look into it

**Comment by sswelm** [comment] 2018-03-13 22:19
Seems to work find to me, going to close it

**Closed by sswelm** 2018-03-13 22:19 UTC
