### ISSUE TITLE
Bizarre levitation of spacecraft when Thermal Power Generator is used

### ISSUE THREAD

**Issue by cgruber** [sswelm/KSP-Interstellar-Extended#1] opened 2016-05-08 11:12 UTC
I have the weirdest behavior, which I've narrowed down to one part - the brayton-cycle thermal power generator.  When that part is present, the spaceships (and spaceplanes) start to float and rotate on the launchpad (runway), and no amount of thrust will alter their position.  

I've found no exceptions in the log, but I did see this difference between a run with the part, and a run without the part.  With the part, I get the following:

```
[LOG 00:38:13.346] [KSPI] - Start Initializing ElectricEngineControllerFX
[LOG 00:38:13.346] [KSPI] - we did not find techid advEMSystems in saved hash
[LOG 00:38:13.346] [KSPI] - we did not find techid specializedPlasmaGeneration in saved hash
[LOG 00:38:13.348] [KSPI] - we did not find techid advEMSystems in saved hash
[LOG 00:38:13.348] [KSPI] - we did not find techid advEMSystems in saved hash
[LOG 00:38:13.348] [KSPI] - we did not find techid specializedPlasmaGeneration in saved hash
[LOG 00:38:13.348] [KSPI] - we did not find techid advEMSystems in saved hash
[LOG 00:38:13.348] [KSPI] - we did not find techid advEMSystems in saved hash
[LOG 00:38:13.348] [KSPI] - we did not find techid advEMSystems in saved hash
[LOG 00:38:13.348] [KSPI] - we did not find techid advEMSystems in saved hash
[LOG 00:38:13.348] [KSPI] - we did not find techid advEMSystems in saved hash
[LOG 00:38:13.348] [KSPI] - End Initializing ElectricEngineControllerFX
```

Without the part, I get no similar message in the logs.  I am using a pebble-bed generator with a thermal launch nozzle but that works fine if the thermal power generator is not used elsewhere in the craft (with it's own, adjacent, thermal source, such as a separate pebble-bed reactor).  

In the end I'm using USI's reactors (which have built in generators and supply MW power now) to work around this and power my plasma nozzles, but they're not as powerful in terms of MW supplied to the engine. And adding that part shound't result in an un-flyable craft.

**Comment by sswelm** [comment] 2016-05-09 09:25
I though I had squased this problem but apparently not. The weird behavior is caused when any parts mass becomes nagative. THis can happen when the delta mass returned by the part except the intial mass. The problem is that initial mass has to be configured correctly otherwise negative mass is generated creating the weird effect. It is on my ASAP list. Might have something to do with the new tweakscale I heard there were some change in the order of applied effects.

**Comment by sswelm** [comment] 2016-06-16 08:36
Should be fixed now, I'm closing for now

**Closed by sswelm** 2016-06-16 08:36 UTC
